name: Detect Simulation File

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'simulations/**.py'

jobs:
  check-simulation:
    runs-on: ubuntu-latest
    steps:
      - name: Write simulation trigger payload
        run: |
          echo "{
            \"pr_number\": \"${{ github.event.pull_request.number }}\",
            \"username\": \"${{ github.actor }}\",
            \"branch\": \"${{ github.head_ref }}\"
          }" > trigger.json

      - name: Upload trigger artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: trigger
          path: trigger.json


