name: Run Simulation on PR

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'simulations/**.py'

jobs:
  run-simulation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H turing >> ~/.ssh/known_hosts
          ssh-keyscan -H baker >> ~/.ssh/known_hosts

      - name: Find Python files in user folder
        id: detect
        run: |
          USERNAME="${{ github.actor }}"
          FILES=$(find simulations/$USERNAME -maxdepth 1 -name "*.py" 2>/dev/null || true)
          if [ -z "$FILES" ]; then
            echo "No simulation files found for $USERNAME"
            echo "found=false" >> $GITHUB_OUTPUT
          else
            echo "Found files: $FILES"
            echo "found=true" >> $GITHUB_OUTPUT
            echo "$FILES" > files_to_copy.txt
          fi

      - name: Copy files to Baker
        if: steps.detect.outputs.found == 'true'
        run: |
          USERNAME="${{ github.actor }}"

          ssh -o ProxyJump=turing baker "mkdir -p ~/simulations/$USERNAME"

          while read file; do
            echo "Copying $file"
            scp -o ProxyJump=turing "$file" baker:~/simulations/$USERNAME/
          done < files_to_copy.txt

