name: Run Simulation on Baker

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'simulations/**.py'

jobs:
  run-simulation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H turing >> ~/.ssh/known_hosts
          ssh-keyscan -H baker >> ~/.ssh/known_hosts

      - name: Copy Python files and script to Baker
        run: |
          USERNAME="${{ github.actor }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"

          ssh -o ProxyJump=turing baker "mkdir -p ~/simulations/$USERNAME"
          
          scp -o ProxyJump=turing simulations/$USERNAME/*.py baker:~/simulations/$USERNAME/
          scp -o ProxyJump=turing .github/scripts/run_and_report.sh baker:~/simulations/$USERNAME/

          ssh -o ProxyJump=turing baker "bash ~/simulations/$USERNAME/run_and_report.sh '$USERNAME' '$PR_NUMBER' '${{ github.repository }}' '${{ secrets.GITHUB_TOKEN }}'"


