name: Run Simulation on Baker

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'simulations/**.py'

jobs:
  run-simulation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH keys and config
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_BASE64 }}" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          echo "
          Host turing
            HostName turing.phas.ubc.ca
            User lukasc
            Port 7743
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null

          Host baker
            User lukasc
            ProxyJump turing
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
          " > ~/.ssh/config

          chmod 600 ~/.ssh/config

      - run: ssh-keygen -l -f ~/.ssh/id_ed25519


      - name: Detect Python files in simulations/<username>/
        id: check_files
        run: |
          USERNAME="${{ github.actor }}"
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"

          # List only added/changed files in simulations/<username>/
          FILES=$(git diff --name-only origin/$BASE_BRANCH...HEAD | grep "^simulations/$USERNAME/.*\.py$" || true)

          if [ -z "$FILES" ]; then
            echo "No matching files found"
            echo "found=false" >> $GITHUB_OUTPUT
          else
            echo "$FILES" > files_to_copy.txt
            echo "found=true" >> $GITHUB_OUTPUT
          fi

      - name: Copy files to Baker
        if: steps.check_files.outputs.found == 'true'
        run: |
          USERNAME="${{ github.actor }}"

          # Create remote directory
          ssh baker "mkdir -p ~/simulations/$USERNAME"

          # Copy files via ProxyJump
          while read file; do
            echo "Copying $file..."
            scp "$file" baker:~/simulations/$USERNAME/
          done < files_to_copy.txt

