name: Resimulate Post-layout simulation verification

on:
  issue_comment:
    types: [created]

jobs:
  resimulate-if-requested:
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, 'please resimulate')
    runs-on: ubuntu-latest

    steps:
      - name: Get PR info
        id: get_pr
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract head ref
        id: extract_ref
        run: |
          echo "ref=$(echo '${{ steps.get_pr.outputs.data }}' | jq -r '.head.ref')" >> $GITHUB_OUTPUT

      - name: Trigger post-layout simulation
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: workflow-run-postlayout-sim.yml
          ref: ${{ steps.extract_ref.outputs.ref }}
          token: ${{ secrets.PAT }}
