name: Secure Simulation via workflow_run (with PR resolution)

on:
  workflow_run:
    workflows: ["Detect Simulation Upload (Fork PR)"]
    types:
      - completed

jobs:
  secure-sim:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout triggering commit
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Get PR number from branch
        id: getpr
        run: |
          echo "Finding PR for branch: ${{ github.event.workflow_run.head_branch }}"
          PR_JSON=$(gh pr list --head "${{ github.event.workflow_run.head_branch }}" --json number -L 1)
          PR_NUMBER=$(echo "$PR_JSON" | jq -r '.[0].number')
          echo "Found PR #: $PR_NUMBER"
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.PAT }}

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keygen -l -f ~/.ssh/id_ed25519 || echo "Invalid SSH key"

      - name: Run Secure Simulation
        run: |
          echo "Simulating for PR #${{ steps.getpr.outputs.pr_number }}..."
          # SSH to baker and execute user's code here

      - name: Post result comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          issue-number: ${{ steps.getpr.outputs.pr_number }}
          body: |
            ✅ Secure simulation completed for PR #${{ steps.getpr.outputs.pr_number }}.
